site_name: Deep Java Library
repo_name: awslabs/djl
repo_url: https://github.com/awslabs/djl/
site_url: https://djl.ai
use_directory_urls: false
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
theme:
  name: material
  logo: website/img/DJL.svg
  favicon: website/img/favicon.png
  features:
    - tabs
  palette:
    primary: light-blue
    accent: light-blue
google_analytics:
  - UA-159559852-2
  - auto
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/awslabs/djl
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/deepjavalibrary
    - icon: fontawesome/brands/slack
      link: https://deepjavalibrary.slack.com/
    - icon: fontawesome/brands/zhihu
      link: https://zhuanlan.zhihu.com/c_1255493231133417472
docs_dir: '../'
plugins:
  - search
  - mknotebooks
  - exclude:
      regex:
        - '.*\.(symbol|params|pt|zip|gz|txt|sh)$'
nav:
  - HOME: 'README.md'
  - 'docs/README.md'
  - 'docs/faq.md'
  - 'docs/how_to_collect_metrics.md'
  - 'docs/load_model.md'
  - 'docs/model-zoo.md'
  - 'docs/quick_start.md'
  - Development:
      - 'docs/development/README.md'
      - 'docs/development/add_model_to_model-zoo.md'
      - 'docs/development/cache_management.md'
      - 'docs/development/configure_logging.md'
      - 'docs/development/development_guideline.md'
      - 'docs/development/how_to_use_dataset.md'
      - 'docs/development/memory_management.md'
      - 'docs/development/release_process.md'
      - 'docs/development/setup.md'
      - 'docs/development/troubleshooting.md'
  - MXNet:
      - 'docs/mxnet/how_to_convert_your_model_to_symbol.md'
      - 'mxnet/README.md'
  - ONNX Runtime:
      - 'docs/onnxruntime/hybrid_engine.md'
  - PyTorch:
      - 'docs/pytorch/how_to_convert_your_model_to_torchscript.md'
      - 'docs/pytorch/how_to_optimize_inference_performance.md'
      - 'pytorch/README.md'
  - TensorFlow:
      - 'docs/tensorflow/how_to_import_keras_models_in_DJL.md'
      - 'docs/tensorflow/how_to_import_local_tensorflow_models.md'
      - 'tensorflow/README.md'

